### ISSUE TITLE
Move from JS to TS

### ISSUE THREAD

**Issue by MikeSquall** [capsulajs/capsula-hub#28]
## General description
The current version of the CapsulaHub app is using pure JS. In order to keep consistency with the [core services](https://github.com/capsulajs/capsulahub-core), we should move to TypeScript and use the provided types.

## Technical considerations
As this change is mainly technical, the test cases will consist into passing the command `yarn lint:ts` which will use `tslint`

## Ready for implementation
- [ ] External dependencies have been resolved
- [ ] API has been approved
- [x] Discussed with Technical lead

## Definition of Done
- [ ] Maintainer review
- [ ] All tests are implemented
- [ ]  Manual QA
- [ ]  Documentation

## RoadMap

In case there is more than one mergeable point you can specify it here.
