### ISSUE TITLE
Add tests

### ISSUE THREAD

**Issue by MikeSquall** [capsulajs/capsula-hub#29]
## General description
The CapsulaHub application is a CLI that allows to run (only one for now but in the future several) commands.

For now, there is no test provided to make sure that everything works fine and there won't be regression in case of new feature.

## Behavior
As this issue is about adding only test cases, it won't change the behavior of the app.

```gherkin
Given An npm package called @capsulajs/capsula-hub
When I install it globally
Then I can run CLI commands
```

## Test cases

https://github.com/capsulajs/capsulahub/pull/33

## Ready for implementation
- [ ] External dependencies have been resolved
- [ ] API has been approved
- [ ] Test cases have been prepared
- [ ] Discussed with Technical lead

## Definition of Done
- [ ] Maintainer review
- [ ] All tests are implemented 
- [ ] Manual QA
- [ ] Documentation
- [ ] Release notes

## RoadMap

In case there is more than one mergeable point you can specify it here.
